# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Lähipeluu
tagline:          'Lähipeluu: luentoja digitaalisista peleistä'
description:      'Lähipeluu: luentoja digitaalisista peleistä'
url:              https://github.com/gitkrax/lahipeluu
baseurl:          '/lahipeluu'

author:
  name:           ''
  url:            

paginate:         5

collections:
  2015:
    output: true
    permalink: /2015/:path/
    
defaults:
  -
    scope:
      path: ""
      type: "2015" # a collection in your site, in plural form
    values:
      layout: "page"

# Custom vars
sidebar_image: img/cover.jpg
version:          

github:
  repo:           
